name: Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP with Composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: highest

      - name: Run unit tests
        run:  vendor/bin/phpunit -c phpunit.xml.dist --testsuite Unit --coverage-clover build/logs/clover.xml --coverage-filter ./src

      - name: Upload codecov coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          files: build/logs/clover.xml
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  feature_tests:
    name: Feature tests
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis/redis-stack-server:${{ matrix.redis_stack }}
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 6379:6379

    strategy:
      fail-fast: false
      matrix:
        redis_stack:
          - latest
          - edge

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP with Composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: highest

      - name: Run feature tests
        run: vendor/bin/phpunit -c phpunit.xml.dist --testsuite Feature
